name: Terraform

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt pytest
      - run: pytest
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [dev, prod]
    env:
      TF_WORKSPACE: ${{ matrix.workspace }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - uses: instrumenta/setup-conftest@v1
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Select Workspace
        run: terraform -chdir=terraform workspace select $TF_WORKSPACE || terraform -chdir=terraform workspace new $TF_WORKSPACE
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: terraform
          additional_args: --minimum-severity HIGH
      - name: Show Plan JSON
        run: terraform -chdir=terraform show -json tfplan > tfplan.json
      - name: Conftest
        run: conftest test tfplan.json
